### ISSUE TITLE
simplepush.send_encrypted crash in python 3.10.4

### ISSUE THREAD

**Issue by michris** [simplepush/simplepush-python#11]
Installed simpepush version 1.2.1 (pip install simplepush)
Python command

import simplepush
simplepush.send_encrypted(device_id, password, salt, message) -> with the correct parameters (all strings) -> crash log:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\site-packages\simplepush\__init__.py", line 63, in send_encrypted
    r = _send_encrypted(key, password, salt, message, title, event, actions)
  File "C:\Python310\lib\site-packages\simplepush\__init__.py", line 81, in _send_encrypted
    return requests.post(SIMPLEPUSH_URL + '/send', json=payload, timeout=DEFAULT_TIMEOUT)
  File "C:\Python310\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "C:\Python310\lib\site-packages\requests\models.py", line 321, in prepare
    self.prepare_body(data, files, json)
  File "C:\Python310\lib\site-packages\requests\models.py", line 473, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "C:\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
>>>

**Comment by simplepush** [comment]
I just released version 1.2.2 and I think it should fix the issue you are seeing.
Could you try again with version 1.2.2?

**Comment by vaygr** [comment]
Works for me. But [aiohttp](https://pypi.org/project/aiohttp/) becomes a hard a dependency that should be mentioned in `setup.py`.
